version: '3.8'

services:
  proxy:
    build: .
    container_name: proxyai-server
    ports:
      - "8080:80"  # Map to port 8080 to avoid conflicts with ChatSite
    restart: unless-stopped
    networks:
      - proxy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  proxy-network:
    driver: bridge
